djing/urls.py
from django.urls import path, include
from django.conf import settings

from .views import home

urlpatterns = [
    path('', home),
    path('accounts/', include('accounts_app.urls', namespace='acc_app')),
    path('abons/', include('abonapp.urls', namespace='abonapp')),
    path('tarifs/', include('tariff_app.urls', namespace='tarifs')),
    path('search/', include('searchapp.urls', namespace='searchapp')),
    path('dev/', include('devapp.urls', namespace='devapp')),
    path('map/', include('mapapp.urls', namespace='mapapp')),
    path('statistic/', include('traf_stat.urls', namespace='traf_stat')),
    path('tasks/', include('taskapp.urls', namespace='taskapp')),
    path('client/', include('clientsideapp.urls', namespace='client_side')),
    path('msg/', include('msg_app.urls', namespace='msg_app')),
    path('groups/', include('group_app.urls', namespace='group_app')),
    path('ip_pool/', include('ip_pool.urls', namespace='ip_pool')),
    path('messenger/', include('messenger.urls', namespace='messenger')),
    path('gw/', include('gw_app.urls', namespace='gw_app')),
    path('new_customers/', include('new_customers.urls', namespace='new_customers')),
    path('fin/', include('finapp.urls', namespace='finapp'))

    # Switch language
    #path(r'i18n/', include('django.conf.urls.i18n')),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.contrib import admin

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(staticfiles_urlpatterns())
    urlpatterns.append(path('admin/', admin.site.urls))

messenger/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from messenger import views


app_name = 'messenger'

urlpatterns = [
    path('', views.MessengerListView.as_view(), name='messengers_list'),
    path('new/', views.AddMessengerCreateView.as_view(), name='add_messenger'),
    path('viber/new/', views.AddMessengerViberCreateView.as_view(), name='add_viber_messenger'),
    path('viber/<slug:slug>/update/', views.UpdateViberMessengerUpdateView.as_view(), name='update_viber_messenger'),
    path('viber/<slug:slug>/delete/', views.RemoveViberMessengerDeleteView.as_view(), name='delete_viber_messenger'),
    path('viber/<slug:slug>/listen/', csrf_exempt(views.ListenViberView.as_view()), name='listen_viber_bot'),
    path('viber/<slug:slug>/set_webhook/', views.SetWebhook.as_view(), name='webhook_viber_bot'),
    path('viber/<slug:slug>/subscribers/', views.SubscribersListView.as_view(), name='subscribers'),
]

messenger/models.py
from urllib.parse import urljoin

from django.conf import settings
from django.shortcuts import resolve_url
from django.utils.translation import gettext_lazy as _
from django.db import models
from viberbot import Api, BotConfiguration
from viberbot.api.messages import TextMessage
from viberbot.api.messages.message import Message

from accounts_app.models import UserProfile


class Messenger(models.Model):
    title = models.CharField(_('Title'), max_length=64)
    CHAT_TYPES = (
        (1, _('Viber')),
    )
    bot_type = models.PositiveSmallIntegerField(_('Bot type'), choices=CHAT_TYPES, blank=True)
    slug = models.SlugField(_('Slug'))

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'messengers'
        verbose_name = _('messenger')
        verbose_name_plural = _('Messengers')
        ordering = ('title',)

    def get_absolute_url(self):
        if self.bot_type == 1:
            return resolve_url('messenger:update_viber_messenger', self.slug)

    def get_next_url(self):
        if self.bot_type == 1:  # Viber
            return resolve_url('messenger:update_viber_messenger', self.slug)
        else:
            return resolve_url('messenger:messengers_list')


class ViberMessenger(Messenger):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._viber_cache = None

    token = models.CharField(_('Bot secret token'), max_length=64)
    avatar = models.ImageField(_('Avatar'), upload_to='viber_avatar', null=True)

    def get_viber(self):
        if self._viber_cache is None:
            self._viber_cache = Api(BotConfiguration(
                name=str(self.slug),
                avatar=self.avatar.url,
                auth_token=str(self.token)
            ))
        return self._viber_cache

    def send_message_to_acc(self, to: UserProfile, msg):
        try:
            viber = self.get_viber()
            vs = to.vibersubscriber
            if issubclass(msg.__class__, Message):
                viber.send_messages(str(vs.uid), msg)
            else:
                viber.send_messages(str(vs.uid), TextMessage(text=msg))
        except ViberSubscriber.DoesNotExist:
            pass

    def send_message_to_accs(self, receivers, msg_text: str):
        """
        :param receivers: QuerySet of accounts_app.UserProfile
        :param msg_text: text message
        :return: nothing
        """
        viber = self.get_viber()
        msg = TextMessage(text=msg_text)
        for vs in ViberSubscriber.objects.filter(account__in=receivers).iterator():
            viber.send_messages(str(vs.uid), msg)

    def send_message_to_id(self, subscriber_id: str, msg):
        viber = self.get_viber()
        if issubclass(msg.__class__, Message):
            viber.send_messages(subscriber_id, msg)
        else:
            viber.send_messages(subscriber_id, TextMessage(text=msg))

    def send_webhook(self):
        pub_url = getattr(settings, 'VIBER_BOT_PUBLIC_URL')
        listen_url = resolve_url('messenger:listen_viber_bot', self.slug)
        public_url = urljoin(pub_url, listen_url)
        viber = self.get_viber()
        viber.set_webhook(public_url, ['failed', 'subscribed', 'unsubscribed', 'conversation_started'])

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'viber_messenger_notifications'
        verbose_name = _('Viber messenger')
        verbose_name_plural = _('Viber messengers')
        ordering = ('title',)


class ViberMessage(models.Model):
    msg = models.TextField(_('Message'))
    date = models.DateTimeField(_('Date'), auto_now_add=True)
    sender = models.CharField(_('Sender'), max_length=32)
    messenger = models.ForeignKey(ViberMessenger, verbose_name=_('messenger'), on_delete=models.CASCADE)
    subscriber = models.ForeignKey('ViberSubscriber', on_delete=models.SET_NULL, verbose_name=_('Subscriber'), null=True)

    def __str__(self):
        return self.msg

    class Meta:
        db_table = 'viber_messages_notifications'
        verbose_name = _('Viber message')
        verbose_name_plural = _('Viber messages')
        ordering = ('-date',)


class ViberSubscriber(models.Model):
    uid = models.CharField(_('User unique id in viber'), max_length=32)
    name = models.CharField(_('Name'), max_length=32, null=True, blank=True)
    avatar = models.URLField(_('Avatar'), max_length=250, null=True, blank=True)
    account = models.OneToOneField(UserProfile, on_delete=models.CASCADE, verbose_name=_('System account'), blank=True, null=True)

    def __str__(self):
        return self.name or 'no'

    class Meta:
        db_table = 'viber_subscriber'
        verbose_name = _('Viber subscriber')
        verbose_name_plural = _('Viber subscribers')
        ordering = ('name',)

messenger/forms.py
from django import forms
from messenger import models


class MessengerForm(forms.ModelForm):
    class Meta:
        model = models.Messenger
        fields = ('bot_type',)


class MessengerViberForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs['initial']['bot_type'] = 1
        super().__init__(*args, **kwargs)
        inst = getattr(self, 'instance')
        if inst:
            self.fields['bot_type'].disabled = True
            #self.fields['bot_type'].widget.attrs['disabled'] = True

    class Meta:
        model = models.ViberMessenger
        fields = '__all__'


class MessengerViberMessageForm(forms.ModelForm):
    class Meta:
        model = models.ViberMessage
        fields = '__all__'

messenger/views.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import HttpResponseForbidden, HttpResponse, HttpResponseNotFound
from django.shortcuts import resolve_url
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _, gettext
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, FormView, View
from django.views.generic.detail import SingleObjectMixin
from viberbot.api.messages import KeyboardMessage, ContactMessage
from viberbot.api.user_profile import UserProfile as ViberUserProfile
from viberbot.api.viber_requests import (
    ViberMessageRequest, ViberSubscribedRequest,
    ViberFailedRequest, ViberUnsubscribedRequest
)

from accounts_app.models import UserProfile
from djing.lib.mixins import LoginAdminPermissionMixin, LoginAdminMixin
from messenger import forms, models

from messenger.models import ViberMessage, ViberSubscriber


class MessengerListView(LoginAdminPermissionMixin, ListView):
    model = models.Messenger
    permission_required = 'messenger.view_messenger'


class AddMessengerCreateView(LoginAdminMixin, FormView):
    template_name = 'messenger/add_messenger.html'
    form_class = forms.MessengerForm

    def form_valid(self, form):
        bot_type = form.cleaned_data.get('bot_type')
        if isinstance(bot_type, int) and bot_type > 0:
            if bot_type == 1:
                self.success_url = resolve_url('messenger:add_viber_messenger')
                return super().form_valid(form)
        messages.info(self.request, _('Unexpected bot type'))
        self.success_url = resolve_url('messenger:messengers_list')
        return super().form_valid(form)


class AddMessengerViberCreateView(LoginAdminMixin, PermissionRequiredMixin, CreateView):
    model = models.ViberMessenger
    form_class = forms.MessengerViberForm
    permission_required = 'messenger.add_vibermessenger'
    success_url = reverse_lazy('messenger:messengers_list')

    def form_valid(self, form):
        r = super().form_valid(form)
        messages.success(self.request, _('New viber messenger successfully created'))
        return r


class UpdateViberMessengerUpdateView(LoginAdminPermissionMixin, UpdateView):
    model = models.ViberMessenger
    form_class = forms.MessengerViberForm
    permission_required = 'messenger.change_vibermessenger'

    def form_valid(self, form):
        r = super().form_valid(form)
        messages.success(self.request, _('Viber messenger successfully updated'))
        return r


class RemoveViberMessengerDeleteView(LoginAdminPermissionMixin, DeleteView):
    model = models.ViberMessenger
    permission_required = 'messenger.delete_vibermessenger'
    success_url = reverse_lazy('messenger:messengers_list')

    def delete(self, request, *args, **kwargs):
        r = super().delete(request, *args, **kwargs)
        messages.success(request, _('Viber messenger successfully deleted'))
        return r


class ListenViberView(SingleObjectMixin, View):
    http_method_names = 'post',
    model = models.ViberMessenger

    def post(self, request, *args, **kwargs):
        obj = self.get_object()
        if not obj:
            return HttpResponseNotFound()
        self.object = obj
        viber = obj.get_viber()
        if not viber.verify_signature(request.body, request.META.get('HTTP_X_VIBER_CONTENT_SIGNATURE')):
            return HttpResponseForbidden()
        vr = viber.parse_request(request.body)
        if isinstance(vr, ViberMessageRequest):
            in_msg = vr.message
            if isinstance(in_msg, ContactMessage):
                self.inbox_contact(in_msg, vr.sender)
            subscriber, created = self.make_subscriber(vr.sender)
            if not created:
                ViberMessage.objects.create(
                    msg=vr.message,
                    sender=vr.sender.id,
                    messenger=obj,
                    subscriber=subscriber
                )
        elif isinstance(vr, ViberSubscribedRequest):
            self.make_subscriber(vr.user)
        elif isinstance(vr, ViberFailedRequest):
            print("client failed receiving message. failure: {0}".format(vr))
        elif isinstance(vr, ViberUnsubscribedRequest):
            ViberSubscriber.objects.filter(
                uid=vr.user_id
            ).delete()
        return HttpResponse(status=200)

    def make_subscriber(self, viber_user_profile: ViberUserProfile):
        subscriber, created = ViberSubscriber.objects.get_or_create(
            uid=viber_user_profile.id,
            defaults={
                'name': viber_user_profile.name,
                'avatar': viber_user_profile.avatar
            }
        )
        if created and hasattr(self, 'object'):
            msg = KeyboardMessage(keyboard={
                'Type': 'keyboard',
                'DefaultHeight': True,
                'Buttons': ({
                    'ActionType': 'share-phone',
                    'ActionBody': 'reply to me',
                    "Text": gettext('My telephone number'),
                    "TextSize": "medium"
                },)
            }, min_api_version=3)
            viber = self.object
            viber.send_message_to_id(viber_user_profile.id, msg)
        return subscriber, created

    def inbox_contact(self, msg, sender: ViberUserProfile):
        tel = msg.contact.phone_number
        accs = UserProfile.objects.filter(telephone__icontains=tel)
        viber = self.object
        if accs.exists():
            first_acc = accs.first()
            subs = ViberSubscriber.objects.filter(uid=sender.id)
            subs_len = subs.count()
            if subs_len > 0:
                first_sub = subs.first()
                if subs_len > 1:
                    ViberSubscriber.objects.exclude(pk=first_sub.pk).delete()
                first_sub.account = first_acc
                first_sub.name = first_acc.get_full_name()
                first_sub.save(update_fields=('account', 'name'))
                viber.send_message_to_acc(first_acc, gettext(
                    'Your account is attached. Now you will be receive notifications from billing'
                ))
        else:
            viber.send_message_to_id(sender.id, gettext(
                'Telephone not found, please specify telephone number in account in billing'
            ))


class SetWebhook(LoginAdminMixin, SingleObjectMixin, View):
    http_method_names = 'get',
    model = models.ViberMessenger

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        if not obj:
            return HttpResponseNotFound
        obj.send_webhook()
        return HttpResponse(b'ok', status=200)


class SubscribersListView(LoginAdminMixin, ListView):
    model = models.ViberSubscriber

    def get_context_data(self, **kwargs):
        context = {
            'messanger_slug': self.kwargs.get('slug')
        }
        context.update(kwargs)
        return super().get_context_data(**context)

messenger/templates/messenger/add_messenger.html
{% load i18n bootstrap3 %}
<form role="form" action="{% url 'messenger:add_messenger' %}" method="post">{% csrf_token %}
    <div class="modal-header primary">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title"><span class="glyphicon glyphicon-blackboard"></span>{% trans 'Select bot type' %}</h4>
    </div>

    <div class="modal-body">
        {% bootstrap_form form %}
        <button type="submit" class="btn btn-success">
            <span class="glyphicon glyphicon-plus"></span> {% trans 'Add' %}
        </button>
    </div>

</form>

messenger/templates/messenger/messenger_list.html
{% extends 'base.html' %}
{% load dpagination i18n %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><span class="glyphicon glyphicon-home"></span></li>
        <li class="active">{% trans 'Messengers' %}</li>
    </ol>
{% endblock %}

{% block page-header %}
    {% trans 'Messengers' %}
{% endblock %}

{% block main %}
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th class="col-sm-4">{% trans 'Title' %}</th>
                <th class="col-sm-3">{% trans 'Type' %}</th>
                <th class="col-sm-4">{% trans 'Slug' %}</th>
                <th class="col-sm-1">#</th>
            </tr>
            </thead>
            <tbody>
            {% for messenger in object_list %}
                <tr>
                    <td>{{ messenger.title }}</td>
                    <td>{{ messenger.get_bot_type_display }}</td>
                    <td>{{ messenger.slug }}</td>
                    <td>
                        <div class="btn-group btn-group-sm">
                            <a href="{{ messenger.get_absolute_url }}" class="btn btn-sm btn-default" title="{% trans 'Edit' %}">
                                <span class="glyphicon glyphicon-edit"></span>
                            </a>
                            <a href="{% url 'messenger:subscribers' messenger.slug %}" class="btn btn-sm btn-default" title="{% trans 'Viber subscribers' %}">
                                <span class="glyphicon glyphicon-ice-lolly"></span>
                            </a>
                        </div>
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="4">{% trans 'Messengers was not found' %}</td>
                </tr>
            {% endfor %}
            </tbody>
            {% if perms.messenger.add_messenger %}
            <tfoot>
            <tr>
                <td colspan="4" class="btn-group btn-group-sm">
                    <a href="{% url 'messenger:add_messenger' %}" class="btn btn-default btn-modal">
                        <span class="glyphicon glyphicon-plus"></span> <span class="hidden-xs">{% trans 'New' %}</span>
                    </a>
                </td>
            </tr>
            </tfoot>
            {% endif %}
        </table>
    </div>
{% endblock %}

messenger/templates/messenger/vibermessenger_form.html
{% extends request.is_ajax|yesno:'bajax.html,base.html' %}
{% load i18n bootstrap3 %}


{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><span class="glyphicon glyphicon-home"></span></li>
        <li><a href="{% url 'messenger:messengers_list' %}">{% trans 'Messengers' %}</a></li>
        {% if object %}
            <li class="active">{% trans 'Change viber' %}</li>
        {% else %}
            <li class="active">{% trans 'Add viber' %}</li>
        {% endif %}

    </ol>
{% endblock %}


{% block main %}

    {% if object %}
        {% url 'messenger:update_viber_messenger' object.slug as form_url %}
        {% trans 'Change messenger' as panel_title %}
    {% else %}
        {% url 'messenger:add_viber_messenger' as form_url %}
        {% trans 'Add new messenger' as panel_title %}
    {% endif %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{{ panel_title }}</h3>
        </div>
        <div class="panel-body">
            <form role="form" action="{{ form_url }}" method="post" enctype="multipart/form-data">{% csrf_token %}
                {% bootstrap_form form %}
                <button type="submit" class="btn btn-sm btn-default">
                    <span class="glyphicon glyphicon-save"></span> {% trans 'Save' %}
                </button>
                {% if object %}
                    <a href="{% url 'messenger:webhook_viber_bot' object.slug %}" class="btn btn-default btn-sm btn-modal">
                        <span class="glyphicon glyphicon-share"></span> {% trans 'Send webhook' %}
                    </a>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}

messenger/templates/messenger/vibersubscriber_list.html
{% extends 'base.html' %}
{% load dpagination i18n %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><span class="glyphicon glyphicon-home"></span></li>
        <li><a href="{% url 'messenger:messengers_list' %}">{% trans 'Messengers' %}</a></li>
        <li class="active">{% trans 'Viber subscribers' %}</li>
    </ol>
{% endblock %}

{% block page-header %}
    {% trans 'Viber subscribers' %}
{% endblock %}

{% block main %}
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th class="col-sm-4">{% trans 'uid' %}</th>
                <th class="col-sm-3">{% trans 'Name' %}</th>
                <th class="col-sm-4">{% trans 'Account' %}</th>
            </tr>
            </thead>
            <tbody>
            {% for subscriber in object_list %}
                <tr>
                    <td>{{ subscriber.uid }}</td>
                    <td>{{ subscriber.name }}</td>
                    <td><a href="{{ subscriber.account.get_absolute_url }}">{{ subscriber.account.get_full_name }}</a></td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="3">{% trans 'Subscribers was not found' %}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}