accounts_app/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import LogoutView

from . import views

app_name = 'account_app'

urlpatterns = [
    path('', views.AccountsListView.as_view(), name='accounts_list'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='acc_app:login'), name='logout'),
    path('login_by_location/', views.location_login, name='llogin'),

    path('add/', views.create_profile, name='create_profile'),

    path('settings/', views.UpdateSelfAccount.as_view(), name='setup_info'),
    path('settings/change_ava/', views.AvatarUpdateView.as_view(), name='setup_avatar'),

    path('<int:uid>/', views.ProfileShowDetailView.as_view(), name='other_profile'),
    path('<int:uid>/edit/', views.UpdateAccount.as_view(), name='edit_profile'),
    path('<int:uid>/perms/', views.PermsUpdateView.as_view(), name='setup_perms'),
    path('<int:uid>/perms/object/', views.perms_object, name='setup_perms_object'),

    re_path('^(?P<uid>\d+)/perms/object/(?P<klass_name>[a-z_]+\.[a-zA-Z_]+)/$', views.PermissionClassListView.as_view(), name='perms_klasses'),

    re_path('^(?P<uid>\d+)/perms/object/(?P<klass_name>[a-z_]+\.[a-zA-Z_]+)/(?P<obj_id>\d+)/$', views.perms_edit, name='perms_edit'),

    path('<int:uid>/del/', views.delete_profile, name='delete_profile'),

    path('<int:uid>/user_group_access/', views.set_abon_groups_permission, name='set_abon_groups_permission'),

    path('<int:uid>/manage_responsibility_groups/', views.ManageResponsibilityGroups.as_view(), name='manage_responsibility_groups'),

    path('<int:uid>/actions/', views.ActionListView.as_view(), name='action_log')
]

djing/urls.py
from django.urls import path, include
from django.conf import settings

from .views import home

urlpatterns = [
    path('', home),
    path('accounts/', include('accounts_app.urls', namespace='acc_app')),
    path('abons/', include('abonapp.urls', namespace='abonapp')),
    path('tarifs/', include('tariff_app.urls', namespace='tarifs')),
    path('search/', include('searchapp.urls', namespace='searchapp')),
    path('dev/', include('devapp.urls', namespace='devapp')),
    path('map/', include('mapapp.urls', namespace='mapapp')),
    path('statistic/', include('traf_stat.urls', namespace='traf_stat')),
    path('tasks/', include('taskapp.urls', namespace='taskapp')),
    path('client/', include('clientsideapp.urls', namespace='client_side')),
    path('msg/', include('msg_app.urls', namespace='msg_app')),
    path('groups/', include('group_app.urls', namespace='group_app')),
    path('ip_pool/', include('ip_pool.urls', namespace='ip_pool')),
    path('messenger/', include('messenger.urls', namespace='messenger')),
    path('gw/', include('gw_app.urls', namespace='gw_app')),
    path('new_customers/', include('new_customers.urls', namespace='new_customers')),
    path('fin/', include('finapp.urls', namespace='finapp'))

    # Switch language
    #path(r'i18n/', include('django.conf.urls.i18n')),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.contrib import admin

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend(staticfiles_urlpatterns())
    urlpatterns.append(path('admin/', admin.site.urls))

accounts_app/forms.py
# -*- coding: utf-8 -*-
from guardian.forms import UserObjectPermissionsForm
from guardian.shortcuts import assign_perm, remove_perm
from django import forms
from .models import UserProfile


class MyUserObjectPermissionsForm(UserObjectPermissionsForm):
    def __init__(self, *args, **kwargs):
        super(MyUserObjectPermissionsForm, self).__init__(*args, **kwargs)
        self.fields['permissions'].widget.attrs.update({
            'size': 15
        })

    def save_obj_perms(self):
        """
        Saves selected object permissions by creating new ones and removing
        those which were not selected but already exists.

        Should be called *after* form is validated.
        """
        perms = set(self.cleaned_data[self.get_obj_perms_field_name()])
        model_perms = set((c[0] for c in self.get_obj_perms_field_choices()))
        init_perms = set(self.get_obj_perms_field_initial())

        to_remove = (model_perms - perms) & init_perms
        for perm in to_remove:
            remove_perm(perm, self.user, self.obj)

        for perm in perms - init_perms:
            assign_perm(perm, self.user, self.obj)


class AvatarChangeForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar',)


class UserPermissionsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserPermissionsForm, self).__init__(*args, **kwargs)
        self.fields['user_permissions'].widget.attrs.update({
            'size': 35
        })

    class Meta:
        model = UserProfile
        fields = ('user_permissions', 'is_superuser')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ('avatar', 'password', 'groups', 'user_permissions',
                   'responsibility_groups', 'is_admin', 'is_superuser', 'last_login')

accounts_app/views.py
from django.apps import apps
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from django.contrib import messages
from django.urls import NoReverseMatch
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from django.views.generic import ListView, UpdateView, DetailView
from django.conf import settings

from group_app.models import Group

from .models import UserProfile, UserProfileLog
from accounts_app import forms
from djing.lib.decorators import only_admins
from djing.lib.mixins import OnlyAdminsMixin, LoginAdminPermissionMixin, OnlySuperUserMixin
from guardian.decorators import permission_required_or_403 as permission_required
from guardian.shortcuts import get_objects_for_user, assign_perm, remove_perm


class CustomLoginView(LoginView):
    template_name = 'accounts/login.html'

    def form_invalid(self, form):
        for msg in form.non_field_errors():
            messages.error(self.request, msg)
        return super().form_invalid(form)

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        if self.request.user.is_staff:
            return resolve_url('acc_app:setup_info')
        return resolve_url('client_side:home')


def location_login(request):
    nextl = request.GET.get('next')
    nextl = '' if nextl == 'None' or nextl is None or nextl.isspace() else nextl
    try:
        auser = authenticate(request=request, byip=None)
        if auser:
            login(request, auser)
            if nextl == 'None' or nextl is None or nextl == '':
                if request.user.is_staff:
                    return redirect('acc_app:setup_info')
                return redirect('client_side:home')
            return redirect(nextl)
        return render(request, 'accounts/login.html', {
            'next': nextl,
            'form': AuthenticationForm()
        })
    except NoReverseMatch:
        return redirect('client_side:home')


class ProfileShowDetailView(LoginRequiredMixin, OnlyAdminsMixin, DetailView):
    model = UserProfile
    pk_url_kwarg = 'uid'
    template_name = 'accounts/index.html'
    context_object_name = 'userprofile'

    def get_context_data(self, **kwargs):
        context = {
            'uid': self.kwargs.get('uid')
        }
        context.update(kwargs)
        return super(ProfileShowDetailView, self).get_context_data(**context)

    def dispatch(self, request, *args, **kwargs):
        uid = self.kwargs.get('uid')
        if uid == 0:
            return redirect('acc_app:other_profile', uid=request.user.id)
        return super(ProfileShowDetailView, self).dispatch(request, *args, **kwargs)


class AvatarUpdateView(LoginRequiredMixin, OnlyAdminsMixin, UpdateView):
    form_class = forms.AvatarChangeForm
    template_name = 'accounts/settings/ch_info.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return resolve_url('acc_app:other_profile', uid=self.request.user.id)


class UpdateAccount(LoginRequiredMixin, OnlySuperUserMixin, UpdateView):
    form_class = forms.UserProfileForm
    pk_url_kwarg = 'uid'
    model = UserProfile
    template_name = 'accounts/settings/userprofile_form.html'

    def form_valid(self, form):
        r = super().form_valid(form)
        messages.success(self.request, _('Saved successfully'))
        return r

    def get_context_data(self, **kwargs):
        context = {
            'form_url': resolve_url('acc_app:edit_profile', self.object.pk)
        }
        context.update(kwargs)
        return super().get_context_data(**context)


class UpdateSelfAccount(LoginRequiredMixin, UpdateView):
    form_class = forms.UserProfileForm
    pk_url_kwarg = 'uid'
    model = UserProfile
    template_name = 'accounts/settings/userprofile_form.html'

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        r = super().form_valid(form)
        messages.success(self.request, _('Saved successfully'))
        return r

    def get_context_data(self, **kwargs):
        context = {
            'form_url': resolve_url('acc_app:setup_info')
        }
        context.update(kwargs)
        return super().get_context_data(**context)


@login_required
@only_admins
@permission_required('accounts_app.add_userprofile')
def create_profile(request):
    if request.method == 'POST':
        username = request.POST.get('username')

        user = UserProfile()
        user.username = username
        user.fio = request.POST.get('fio')
        user.email = request.POST.get('email')
        user.telephone = request.POST.get('telephone')
        user.is_admin = True

        passwd = request.POST.get('passwd')
        conpasswd = request.POST.get('conpasswd')
        if not passwd:
            messages.error(request, _('You forget specify a password for the new account'))

        if not conpasswd:
            messages.error(request, _('You forget to repeat a password for the new account'))

        if passwd == conpasswd:
            user_qs = UserProfile.objects.filter(username=username)[:1]
            if user_qs.count() == 0:
                user.set_password(passwd)
                user.save()
                return redirect('acc_app:accounts_list')
            else:
                messages.error(request, _('Subscriber with this name already exist'))
        else:
            messages.error(request, _('Passwords does not match, try again'))
        return render(request, 'accounts/create_acc.html', {
            'newuser': user
        })
    return render(request, 'accounts/create_acc.html')


@login_required
@only_admins
def delete_profile(request, uid: int):
    prf = get_object_or_404(UserProfile, id=uid)
    if uid != request.user.id:
        if not request.user.has_perm('acc_app.delete_userprofile', prf):
            raise PermissionDenied
    prf.delete()
    messages.success(request, _('Profile has been deleted'))
    return redirect('acc_app:accounts_list')


class AccountsListView(LoginRequiredMixin, OnlyAdminsMixin, ListView):
    http_method_names = 'get',
    paginate_by = getattr(settings, 'PAGINATION_ITEMS_PER_PAGE', 10)
    template_name = 'accounts/acc_list.html'
    context_object_name = 'users'

    def get_queryset(self):
        users = UserProfile.objects.filter(is_admin=True).exclude(pk=self.request.user.pk)
        users = get_objects_for_user(self.request.user, 'accounts_app.view_userprofile', users)
        return users


@login_required
def perms_object(request, uid: int):
    if not request.user.is_superuser:
        raise PermissionDenied
    userprofile = get_object_or_404(UserProfile, id=uid)
    klasses = (
        'abonapp.Abon', 'accounts_app.UserProfile',
        'abonapp.AbonTariff', 'abonapp.AbonStreet', 'devapp.Device',
        'abonapp.PassportInfo', 'abonapp.AdditionalTelephone', 'tariff_app.PeriodicPay',
        'group_app.Group'
    )
    return render(request, 'accounts/perms/object/objects_types.html', {
        'userprofile': userprofile,
        'klasses': klasses
    })


@method_decorator(login_required, name='dispatch')
class PermsUpdateView(UpdateView):
    http_method_names = 'get', 'post'
    template_name = 'accounts/perms/change_global_perms.html'
    model = UserProfile
    form_class = forms.UserPermissionsForm
    pk_url_kwarg = 'uid'

    def get_success_url(self):
        return resolve_url('acc_app:setup_perms', self.userprofile.pk)

    def get_object(self, queryset=None):
        self.userprofile = get_object_or_404(UserProfile, id=self.kwargs.get('uid'))
        return super(PermsUpdateView, self).get_object(queryset=queryset)

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            raise PermissionDenied
        return super(PermsUpdateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            'userprofile': self.userprofile
        }
        context.update(kwargs)
        return super(PermsUpdateView, self).get_context_data(**context)

    def form_valid(self, form):
        messages.success(self.request, _('Permissions has successfully updated'))
        return super(PermsUpdateView, self).form_valid(form)


class PermissionClassListView(LoginRequiredMixin, OnlyAdminsMixin, ListView):
    http_method_names = 'get',
    paginate_by = getattr(settings, 'PAGINATION_ITEMS_PER_PAGE', 10)
    template_name = 'accounts/perms/object/objects_of_type.html'
    context_object_name = 'objects'

    def get(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            raise PermissionDenied
        return super(PermissionClassListView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(PermissionClassListView, self).get_context_data(**kwargs)
        context['klass'] = self.kwargs.get('klass_name')
        context['klass_name'] = self.required_klass_name._meta.verbose_name
        context['userprofile'] = get_object_or_404(UserProfile, pk=self.kwargs.get('uid'))
        return context

    def get_queryset(self):
        klass_name = self.kwargs.get('klass_name')
        app_label, model_name = klass_name.split('.', 1)
        klass = apps.get_model(app_label, model_name)
        objects = klass.objects.all()
        self.required_klass_name = klass
        return objects


@login_required
@only_admins
def perms_edit(request, uid: int, klass_name, obj_id):

accounts_app/templates/accounts/perms/object/objects_of_type.html
{% extends request.is_ajax|yesno:'nullcont.htm,accounts/perms/ext.html' %}
{% load i18n %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><span class="glyphicon glyphicon-home"></span></li>
        <li><a href="{% url 'acc_app:accounts_list' %}">{% trans 'Administrators' %}</a></li>
        <li><a href="{% url 'acc_app:other_profile' userprofile.pk %}">{{ userprofile.username }}</a></li>
        <li><a href="{% url 'acc_app:setup_perms_object' userprofile.pk %}">{% trans 'Object permission options' %}</a></li>
        <li class="active">&lt;{{ klass }}&gt; {{ klass_name }}</li>
    </ol>
{% endblock %}


{% block page-header %}
    {% trans 'Pick object for edit permissions' %}
{% endblock %}


{% block main %}
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>obj</th>
            </tr>
            </thead>
            <tbody>
            {% for obj in objects %}<tr><td>
                <a href="{% url 'acc_app:perms_edit' userprofile.pk klass obj.pk %}">{{ obj }}</a>
            </td></tr>{% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

accounts_app/templates/accounts/perms/object/objects_types.html
{% extends request.is_ajax|yesno:'nullcont.htm,accounts/perms/ext.html' %}
{% load i18n acc_tags %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><span class="glyphicon glyphicon-home"></span></li>
        <li><a href="{% url 'acc_app:accounts_list' %}">{% trans 'Administrators' %}</a></li>
        <li><a href="{% url 'acc_app:other_profile' userprofile.pk %}">{{ userprofile.username }}</a></li>
        <li><a href="{% url 'acc_app:setup_perms_object' userprofile.pk %}">{% trans 'Object permission options' %}</a></li>
        <li class="active">{% trans 'Object permission options' %}</li>
    </ol>
{% endblock %}

{% block page-header %}
    {% trans 'Pick the type of object' %}
{% endblock %}

{% block content %}
    <div class="table-responsive">
        <table class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>{% trans 'Group' %}</th>
            </tr>
            </thead>
            <tbody>
            {% for klass in klasses %}
                <tr>
                    <td>
                        <a href="{% url 'acc_app:perms_klasses' userprofile.pk klass %}">&lt;{{ klass }}&gt; {% klass_name klass %}</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

accounts_app/templates/accounts/perms/object/perms_edit.html
{% extends 'base.html' %}
{% load i18n bootstrap3 %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><span class="glyphicon glyphicon-home"></span></li>
        <li><a href="{% url 'acc_app:accounts_list' %}">{% trans 'Administrators' %}</a></li>
        <li><a href="{% url 'acc_app:other_profile' userprofile.pk %}">{{ userprofile.username }}</a></li>
        <li><a href="{% url 'acc_app:setup_perms_object' userprofile.pk %}">{% trans 'Object permission options' %}</a></li>
        <li><a href="{% url 'acc_app:perms_klasses' userprofile.pk klass %}">&lt;{{ klass }}&gt; {{ klass_name }}</a></li>
        <li class="active">{{ obj }}</li>
    </ol>
{% endblock %}


{% block page-header %}
    {% trans 'Pick object for edit permissions' %}
{% endblock %}


{% block main %}
    {% if userprofile.is_superuser %}
        <div class="alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <span class="glyphicon glyphicon-info-sign"></span>
            {% trans 'Profile is superuser, permissions to change it makes no sense' %}
        </div>
    {% endif %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{% trans 'Change permission for that object' %}</h3>
        </div>
        <div class="panel-body">

            <form role="form" action="{% url 'acc_app:perms_edit' userprofile.pk klass obj.pk %}" method="post">{% csrf_token %}

            {% bootstrap_form form %}

            <div class="btn-group">
                <button type="submit" class="btn btn-sm btn-primary">
                    <span class="glyphicon glyphicon-save"></span> {% trans 'Save' %}
                </button>
                <button type="reset" class="btn btn-sm btn-default">
                    <span class="glyphicon glyphicon-remove-circle"></span> {% trans 'Reset' %}
                </button>
            </div>
            </form>
        </div>
    </div>
{% endblock %}